### ISSUE TITLE
Need a better processor!

### ISSUE THREAD

**Issue by hover2pi** [jradavenport/FFIorBUST#2]
Jim, 

I'm pretty sure it works, though my computer is too slow! Also our one exposure only lets us make light curves with one data point. I'll download a few more exposures from MAST to make sure before doing all 85.

The bottle neck is that it uses the KIC to identify objects but it has 13 million sources. This means it is running a k-d tree search 13 million times on an input catalog of 13 million sources... 85 times. Slow slow slow!

To make it faster, I'll punch out a postage stamp the size of the search radius centered on the coordinates given by the KIC. Then we'll only be doing 13 million times ~10 times 85 cross matches.

That being said, when this works we'll have millions of light curves. Is there a transit depth threshold we should test for before plotting, say 2 sigma or something? This way we'll only get clear transit detections when we run the analysis rather than mostly straight lines.

Let me know if this sounds good and how you all want to proceed!
- Joe

**Comment by jradavenport** [comment]
Awesome! I'll try spinning the code up on my work computer, which is pretty quick. I also have all 53 of the FFIs downloaded there!

We should definitely think about what the most efficient way to match to the KIC is. Maybe doing all the FFIs first and making one huge master table of all sources to cluster? I will muse about this some more... But yes, we definitely expect millions of light curves!

I've been thinking about what to with said light curves. Searching for transits is a good idea, but will be a low yield game. I was thinking of having an undergrad search for eclipsing binaries using Lomb Scargle. I know Lucianne will be interested in transients. Some folks have mentioned looking for parallax. So much to possible look at. Basically anything you want to study is open season, so just call dibs!

I'll send a message later this week setting up a Google Hangout or something to talk more!

---

**Comment by jradavenport** [comment]
Let's try to speed things up by only matching data within a single extension.

Warning: might the extension number a star falls on change very quarter when the spacecraft rolls?

**Comment by bsipocz** [comment]
> Warning: might the extension number a star falls on change very quarter when the spacecraft rolls?

If it does, we only need a look-up table/dictionary to find the matching pair first (or just simply double check the centre coordinates of the extension from the header)
