### ISSUE TITLE
Set goals for project, assign tasks

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/FFIorBUST#3]
We should have a Google Hangout session to discuss the goals for the project. I am busy most of this week, but can find a time late this week or next.

People who might be interested:
@hover2pi @bsipocz @lmwalkowicz @drjenncash @barentsen

**Comment by drjenncash** [comment]
Next week would be a little better for me, but I would definitely like to continue on the project.

**Comment by hover2pi** [comment]
Here's a Doodle poll for next week: http://doodle.com/poll/uf6iegyhpch7iuki

Share with any interested parties!

**Comment by hover2pi** [comment]
Looks like Thursday January 21st at 1 or 2pm EST could be good. Does that work for you, Jim and Lucianne?

**Comment by drjenncash** [comment]
that works for me...  Jennifer

**Comment by jradavenport** [comment]
1pm EST on Thursday works for me!

**Comment by hover2pi** [comment]
Hi folks! I updated the Doodle Poll with a conflict I had but wanted to make sure everyone got it. Is Wednesday at 4pm EST ok with everyone still? It's the only time we all had open.

**Comment by bsipocz** [comment]
Wednesday is OK with me.

**Comment by lmwalkowicz** [comment]
I am good Weds at 3pm Central/4pm EST!
L

**Comment by jradavenport** [comment]
Wednesday at 4pm EST, 1pm PST works for me too!

**Comment by drjenncash** [comment]
That will also work for me

**Comment by barentsen** [comment]
Would love to join!  Time works.

**Comment by jradavenport** [comment]
Reminder: We'e chatting today at 1pm PST / 3PM Central / 4PM EST. I will post a link to the Google Hangout here after lunch!

**Comment by bsipocz** [comment]
+and 9PM GMT

**Comment by jradavenport** [comment]
:+1:

**Comment by jradavenport** [comment]
https://hangouts.google.com/call/7dfda533atiazc2arvx7gcfooya
